### PR TITLE
Feature/update dependencies

### PR DESCRIPTION
**Pull request by nitzan-madar**
### Description
🚨 Review the [guidelines for contributing](../CONTRIBUTING.md) to this repository. 🚨

updating dependencies for security.

### Checklist
Please check if your PR fulfills the following requirements:
- [x] Code compiles correctly (`npm run build`)
- [x] Code is linted
- [x] Created tests which fail without the change (if possible) 
- All **relevant** tests are passing
  - [x] Server Unit Tests
  - [x] Client Unit Tests
  - [x] Achievements Unit Tests
  - [x] API Tests
  - [x] E2E Tests
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by thatkookooguy — APPROVED** [review]

**Comment by Thatkookooguy** [comment]
https://github.com/all-contributors please add @nitzan-madar for code

**Comment by Thatkookooguy** [comment]
@all-contributors please add @nitzan-madar for code

**Pull request merged**
